SELECT 'CREATE DATABASE dss'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dss')\gexec

CREATE TABLE IF NOT EXISTS "User"
(
    UserID VARCHAR(128) NOT NULL UNIQUE PRIMARY KEY,
	USERNAME TEXT NOT NULL,
	Email VARCHAR(320) NOT NULL UNIQUE,
    Fname TEXT NOT NULL,
    Lname TEXT NOT NULL,
    DoB DATE NOT NULL,
    Email_Confirmed BOOLEAN DEFAULT FALSE NOT NULL,
    Account_Status BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Password"
(
    UserID VARCHAR(128) PRIMARY KEY,
    Password VARCHAR(128) NOT NULL,
    Salt VARCHAR(128) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES "User" (UserID) ON DELETE CASCADE
);

/* POST TABLE IN PROGRESS
CREATE TABLE IF NOT EXISTS "Posts"
(
    PostID INT PRIMARY KEY,
    UserID INT,
    Title VARCHAR(100),
    Content TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
)
*/

/*   MAKES TABLES 
SET search_path TO public;

CREATE TABLE IF NOT EXISTS "User"
(
    UserID VARCHAR(128) NOT NULL UNIQUE PRIMARY KEY,
	USERNAME TEXT NOT NULL,
	Email VARCHAR(320) NOT NULL UNIQUE,
    Fname TEXT NOT NULL,
    Lname TEXT NOT NULL,
    DoB DATE NOT NULL,
    Email_Confirmed BOOLEAN DEFAULT FALSE NOT NULL,
    Account_Status BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Password"
(
    UserID VARCHAR(128) PRIMARY KEY,
    Password VARCHAR(128) NOT NULL,
    Salt VARCHAR(128) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES "User" (UserID) ON DELETE CASCADE
);
*/