SELECT 'CREATE DATABASE dss'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dss')\gexec

CREATE TABLE IF NOT EXISTS "User"
(
    UserID VARCHAR(128) NOT NULL UNIQUE PRIMARY KEY,
    Email VARCHAR(320) NOT NULL UNIQUE,
    Fname TEXT NOT NULL,
    Lname TEXT NOT NULL,
    DoB TEXT NOT NULL,
    Email_Confirmed BIT DEFAULT B'0' NOT NULL,
    Account_Status BIT DEFAULT B'0' NOT NULL
);

CREATE TABLE IF NOT EXISTS Password
(
    UserID VARCHAR(128) PRIMARY KEY,
    Password VARCHAR(64) NOT NULL,
    Salt VARCHAR(64) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES "User"(UserID) ON DELETE CASCADE
);