import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/ui/navbar";
import Sidebar from "@/components/ui/sidebar"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DSS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-max">
        <Sidebar/>
        {children}
        </div>
      </body>
    </html>
  );
}
