import Sidebar from "@/components/ui/sidebar"


export const metadata = {
  title: "DSS",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className="flex">
        <Sidebar/>
        {children}
    </div>
  );
}